services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags:
            - { name: 'controller.service_arguments' }
